"""Development seed for the canonical occupation ontology — deliberately
diverse: trades, clinical, legal, financial, military, agricultural, retail,
industrial and knowledge work. This flows through the ingestion pipeline like
any other source; the DATABASE is the runtime truth, not this file.

External mappings use real O*NET-SOC codes where they exist; canonical IDs are
UNBIFY's own and never coupled to one external taxonomy.
"""

CAPABILITIES = [
    ("electrical_diagnosis", "diagnosing electrical systems and faults"),
    ("installation_work", "installing physical systems and equipment"),
    ("safety_procedures", "working under formal safety procedure"),
    ("physical_execution", "skilled hands-on physical work"),
    ("customer_interaction", "working directly with customers/clients"),
    ("estimating_pricing", "estimating and pricing work"),
    ("field_problem_solving", "solving problems on-site under constraints"),
    ("regulatory_navigation", "working within codes, regulation and compliance"),
    ("equipment_operation", "operating machinery and specialized equipment"),
    ("crew_supervision", "supervising small crews and apprentices"),
    ("clinical_assessment", "assessing patients clinically"),
    ("patient_care", "direct patient care"),
    ("medication_management", "managing medication and treatment plans"),
    ("counseling_support", "supporting people through difficulty"),
    ("legal_analysis", "analyzing law and legal risk"),
    ("contract_drafting", "drafting and negotiating agreements"),
    ("dispute_resolution", "resolving disputes and representing interests"),
    ("financial_controls", "maintaining financial controls and accuracy"),
    ("bookkeeping", "keeping accurate financial records"),
    ("tax_compliance", "tax rules and filings"),
    ("financial_analysis", "analyzing financial performance"),
    ("teaching_instruction", "teaching and instructing others"),
    ("curriculum_design", "designing learning material"),
    ("logistics_planning", "planning movement of goods and people"),
    ("procurement", "sourcing and buying under constraints"),
    ("inventory_management", "managing stock and supply"),
    ("fleet_operations", "keeping vehicle fleets operational"),
    ("risk_management", "assessing and managing operational risk"),
    ("crisis_response", "acting effectively in disrupted conditions"),
    ("people_leadership", "leading and being responsible for people"),
    ("training_delivery", "training others in practical skills"),
    ("design_engineering", "engineering design and calculation"),
    ("project_management", "planning and delivering projects"),
    ("site_supervision", "supervising physical work sites"),
    ("software_construction", "building software"),
    ("systems_troubleshooting", "troubleshooting technical systems"),
    ("sales_selling", "selling and closing"),
    ("customer_acquisition", "finding and winning customers"),
    ("merchandising", "choosing and presenting stock"),
    ("crop_livestock_management", "managing crops or livestock"),
    ("machinery_maintenance", "maintaining machines and vehicles"),
    ("process_operation", "running production processes"),
    ("quality_inspection", "inspecting output against standards"),
    ("business_administration", "running the paperwork of a business"),
    ("scheduling_dispatch", "scheduling people and jobs"),
    ("writing_composition", "writing for an audience"),
    ("visual_design", "designing how things look"),
]

INDUSTRIES = [
    ("construction", "Construction"), ("healthcare", "Healthcare"),
    ("legal_services", "Legal services"), ("financial_services", "Financial services"),
    ("education", "Education"), ("manufacturing", "Manufacturing"),
    ("agriculture", "Agriculture"), ("retail", "Retail"),
    ("logistics", "Logistics & supply chain"), ("energy", "Energy"),
    ("software", "Software"), ("public_sector", "Public sector & defense"),
    ("facilities", "Facilities & maintenance"), ("automotive", "Automotive"),
]

# id, label, work_class, pathways, regulated, self_emp, ai_exposure, ai_augment,
# aliases, onet, capabilities [(cap, weight)], environments
OCCUPATIONS = [
    ("occupation_unbify_elec", "Electrician", "trade",
     ["employment", "specialization", "contracting", "business_ownership", "training", "inspection"],
     True, 0.55, 0.15, 0.45,
     ["electrical technician", "maintenance electrician", "electrical maintenance technician"],
     "47-2111.00",
     [("electrical_diagnosis", 1.0), ("installation_work", 0.9), ("safety_procedures", 0.9),
      ("physical_execution", 0.8), ("field_problem_solving", 0.8), ("customer_interaction", 0.6),
      ("estimating_pricing", 0.5), ("regulatory_navigation", 0.7), ("crew_supervision", 0.4)],
     ["site", "field", "residential", "industrial"]),
    ("occupation_unbify_elec_ind", "Industrial Electrician", "trade",
     ["employment", "specialization", "contracting"],
     True, 0.35, 0.15, 0.5,
     ["industrial maintenance electrician"], "47-2111.00",
     [("electrical_diagnosis", 1.0), ("equipment_operation", 0.8), ("safety_procedures", 1.0),
      ("machinery_maintenance", 0.7), ("field_problem_solving", 0.8)],
     ["industrial", "plant"]),
    ("occupation_unbify_solar", "Solar Installation Technician", "trade",
     ["employment", "contracting", "business_ownership"],
     True, 0.4, 0.1, 0.5,
     ["solar installer", "pv installer"], "47-2231.00",
     [("installation_work", 1.0), ("electrical_diagnosis", 0.7), ("safety_procedures", 0.8),
      ("physical_execution", 0.8), ("customer_interaction", 0.5)],
     ["field", "rooftop"]),
    ("occupation_unbify_plumber", "Plumber", "trade",
     ["employment", "specialization", "contracting", "business_ownership", "training"],
     True, 0.6, 0.1, 0.35,
     ["plumbing technician", "pipefitter"], "47-2152.00",
     [("installation_work", 0.9), ("field_problem_solving", 0.9), ("physical_execution", 0.9),
      ("customer_interaction", 0.7), ("estimating_pricing", 0.6), ("regulatory_navigation", 0.6)],
     ["residential", "site", "field"]),
    ("occupation_unbify_carpenter", "Carpenter", "trade",
     ["employment", "contracting", "business_ownership", "specialization"],
     False, 0.6, 0.15, 0.35,
     ["joiner", "finish carpenter", "framing carpenter"], "47-2031.00",
     [("physical_execution", 1.0), ("installation_work", 0.8), ("estimating_pricing", 0.6),
      ("customer_interaction", 0.6), ("field_problem_solving", 0.7)],
     ["site", "workshop"]),
    ("occupation_unbify_welder", "Welder", "trade",
     ["employment", "specialization", "contracting"],
     False, 0.35, 0.3, 0.4,
     ["fabricator", "welding technician"], "51-4121.00",
     [("physical_execution", 1.0), ("equipment_operation", 0.9), ("safety_procedures", 0.9),
      ("quality_inspection", 0.6)],
     ["workshop", "industrial", "site"]),
    ("occupation_unbify_mechanic", "Vehicle Mechanic", "trade",
     ["employment", "specialization", "business_ownership"],
     False, 0.5, 0.25, 0.5,
     ["automotive technician", "auto mechanic"], "49-3023.00",
     [("machinery_maintenance", 1.0), ("systems_troubleshooting", 0.8), ("customer_interaction", 0.6),
      ("equipment_operation", 0.7), ("estimating_pricing", 0.5)],
     ["workshop"]),
    ("occupation_unbify_nurse", "Registered Nurse", "clinical",
     ["employment", "specialization", "training", "part_time"],
     True, 0.1, 0.1, 0.5,
     ["staff nurse", "rn"], "29-1141.00",
     [("patient_care", 1.0), ("clinical_assessment", 0.9), ("medication_management", 0.8),
      ("crisis_response", 0.7), ("counseling_support", 0.6), ("teaching_instruction", 0.4)],
     ["clinical", "hospital"]),
    ("occupation_unbify_physician", "Physician", "clinical",
     ["employment", "specialization", "practice_ownership", "teaching", "advisory"],
     True, 0.3, 0.1, 0.6,
     ["doctor", "medical doctor", "general practitioner"], "29-1215.00",
     [("clinical_assessment", 1.0), ("patient_care", 0.9), ("medication_management", 0.9),
      ("regulatory_navigation", 0.7), ("teaching_instruction", 0.5)],
     ["clinical", "hospital", "practice"]),
    ("occupation_unbify_psychiatrist", "Psychiatrist", "clinical",
     ["employment", "practice_ownership", "teaching", "advisory", "part_time"],
     True, 0.35, 0.05, 0.5,
     [], "29-1223.00",
     [("clinical_assessment", 1.0), ("counseling_support", 0.9), ("medication_management", 0.9),
      ("regulatory_navigation", 0.7)],
     ["clinical", "practice"]),
    ("occupation_unbify_lawyer", "Lawyer", "knowledge",
     ["employment", "practice_ownership", "specialization", "advisory", "consulting"],
     True, 0.4, 0.35, 0.7,
     ["attorney", "solicitor", "advocate"], "23-1011.00",
     [("legal_analysis", 1.0), ("contract_drafting", 0.8), ("dispute_resolution", 0.8),
      ("regulatory_navigation", 0.9), ("customer_interaction", 0.6)],
     ["office", "court"]),
    ("occupation_unbify_accountant", "Accountant", "knowledge",
     ["employment", "practice_ownership", "consulting", "specialization", "part_time"],
     True, 0.45, 0.5, 0.75,
     ["chartered accountant", "cpa", "bookkeeper"], "13-2011.00",
     [("financial_controls", 1.0), ("bookkeeping", 0.9), ("tax_compliance", 0.9),
      ("financial_analysis", 0.8), ("regulatory_navigation", 0.7), ("business_administration", 0.6)],
     ["office", "remote"]),
    ("occupation_unbify_teacher", "School Teacher", "knowledge",
     ["employment", "specialization", "training", "part_time", "independent_tutoring"],
     True, 0.2, 0.15, 0.6,
     ["educator", "schoolteacher"], "25-2021.00",
     [("teaching_instruction", 1.0), ("curriculum_design", 0.8), ("counseling_support", 0.5),
      ("people_leadership", 0.5)],
     ["classroom"]),
    ("occupation_unbify_civileng", "Civil Engineer", "knowledge",
     ["employment", "consulting", "specialization", "project_leadership"],
     True, 0.3, 0.25, 0.6,
     ["structural engineer", "site engineer"], "17-2051.00",
     [("design_engineering", 1.0), ("project_management", 0.8), ("site_supervision", 0.7),
      ("regulatory_navigation", 0.7), ("field_problem_solving", 0.6)],
     ["office", "site"]),
    ("occupation_unbify_mecheng", "Mechanical Engineer", "knowledge",
     ["employment", "consulting", "specialization"],
     False, 0.25, 0.3, 0.65,
     ["design engineer", "maintenance engineer"], "17-2141.00",
     [("design_engineering", 1.0), ("machinery_maintenance", 0.6), ("systems_troubleshooting", 0.7),
      ("project_management", 0.6)],
     ["office", "plant"]),
    ("occupation_unbify_software", "Software Engineer", "knowledge",
     ["employment", "freelancing", "consulting", "product_building", "specialization"],
     False, 0.35, 0.45, 0.9,
     ["software developer", "application developer", "backend engineer", "web developer"],
     "15-1252.00",
     [("software_construction", 1.0), ("systems_troubleshooting", 0.8), ("design_engineering", 0.5),
      ("project_management", 0.4)],
     ["office", "remote"]),
    ("occupation_unbify_sales", "Sales Professional", "service",
     ["employment", "specialization", "freelancing", "business_ownership"],
     False, 0.35, 0.35, 0.7,
     ["sales representative", "account executive", "sales executive"], "41-4012.00",
     [("sales_selling", 1.0), ("customer_acquisition", 0.9), ("customer_interaction", 0.9),
      ("business_administration", 0.4)],
     ["office", "field"]),
    ("occupation_unbify_shopowner", "Shop Owner", "service",
     ["business_ownership", "specialization", "part_time"],
     False, 1.0, 0.3, 0.6,
     ["retailer", "store owner", "shopkeeper"], "41-1011.00",
     [("merchandising", 0.9), ("customer_interaction", 0.9), ("inventory_management", 0.8),
      ("business_administration", 0.8), ("customer_acquisition", 0.7), ("sales_selling", 0.7)],
     ["shop"]),
    ("occupation_unbify_farmer", "Farmer", "field",
     ["business_ownership", "specialization", "part_time", "training"],
     False, 0.9, 0.25, 0.5,
     ["agriculturist", "grower"], "11-9013.00",
     [("crop_livestock_management", 1.0), ("machinery_maintenance", 0.7), ("business_administration", 0.6),
      ("physical_execution", 0.8), ("risk_management", 0.6)],
     ["field", "outdoor"]),
    ("occupation_unbify_millog", "Military Logistics Officer", "operational",
     ["employment", "advisory", "consulting", "training", "operations_transition"],
     False, 0.15, 0.2, 0.6,
     ["army logistics officer", "supply officer", "quartermaster"], "55-1015.00",
     [("logistics_planning", 1.0), ("procurement", 0.9), ("inventory_management", 0.8),
      ("fleet_operations", 0.7), ("people_leadership", 0.9), ("risk_management", 0.8),
      ("crisis_response", 0.8), ("training_delivery", 0.7)],
     ["field", "operational"]),
    ("occupation_unbify_factoryop", "Factory Operator", "operational",
     ["employment", "specialization", "quality_path"],
     False, 0.05, 0.6, 0.4,
     ["production operator", "machine operator", "plant operator"], "51-9198.00",
     [("process_operation", 1.0), ("equipment_operation", 0.8), ("quality_inspection", 0.6),
      ("safety_procedures", 0.7)],
     ["plant"]),
    ("occupation_unbify_facilities", "Facilities Maintenance Technician", "trade",
     ["employment", "contracting", "specialization"],
     False, 0.3, 0.2, 0.5,
     ["facility technician", "building maintenance technician"], "49-9071.00",
     [("systems_troubleshooting", 0.8), ("machinery_maintenance", 0.7), ("installation_work", 0.6),
      ("electrical_diagnosis", 0.5), ("scheduling_dispatch", 0.4), ("safety_procedures", 0.7)],
     ["buildings", "site"]),
    ("occupation_unbify_supplychain", "Supply Chain Coordinator", "operational",
     ["employment", "consulting", "advisory", "specialization"],
     False, 0.2, 0.35, 0.7,
     ["logistics coordinator", "supply chain analyst", "operations coordinator"], "13-1081.00",
     [("logistics_planning", 1.0), ("inventory_management", 0.9), ("procurement", 0.8),
      ("scheduling_dispatch", 0.7), ("financial_analysis", 0.4)],
     ["office", "warehouse"]),
    ("occupation_unbify_trainer", "Vocational Trainer", "service",
     ["employment", "freelancing", "business_ownership", "part_time"],
     False, 0.5, 0.15, 0.6,
     ["technical trainer", "skills instructor", "apprenticeship trainer"], "25-1194.00",
     [("training_delivery", 1.0), ("teaching_instruction", 0.9), ("curriculum_design", 0.6),
      ("people_leadership", 0.5)],
     ["classroom", "workshop", "site"]),
]

# specialization / transition / independent-practice edges (capability-grounded)
TRANSITIONS = [
    ("occupation_unbify_elec", "occupation_unbify_elec_ind", "specialization",
     "shared electrical diagnosis + industrial safety exposure", 0.8),
    ("occupation_unbify_elec", "occupation_unbify_solar", "specialization",
     "installation + electrical capability transfers directly to PV work", 0.75),
    ("occupation_unbify_elec", "occupation_unbify_facilities", "transition",
     "diagnosis and installation transfer into building systems", 0.6),
    ("occupation_unbify_elec", "occupation_unbify_trainer", "transition",
     "experienced tradespeople train apprentices", 0.5),
    ("occupation_unbify_plumber", "occupation_unbify_facilities", "transition",
     "field installation and troubleshooting transfer", 0.55),
    ("occupation_unbify_mechanic", "occupation_unbify_facilities", "transition",
     "machinery maintenance transfers to building equipment", 0.5),
    ("occupation_unbify_millog", "occupation_unbify_supplychain", "transition",
     "logistics, procurement and inventory management transfer directly", 0.85),
    ("occupation_unbify_millog", "occupation_unbify_trainer", "transition",
     "training delivery and people leadership transfer", 0.6),
    ("occupation_unbify_nurse", "occupation_unbify_trainer", "transition",
     "clinical teaching transfers to health education", 0.5),
    ("occupation_unbify_accountant", "occupation_unbify_supplychain", "transition",
     "controls and analysis transfer to operations coordination", 0.4),
    ("occupation_unbify_teacher", "occupation_unbify_trainer", "transition",
     "instruction and curriculum design transfer to vocational training", 0.7),
    ("occupation_unbify_welder", "occupation_unbify_trainer", "transition",
     "certified welders train and certify others", 0.45),
]

PROBLEMS = [
    ("problem_ev_charging", "EV charging infrastructure build-out needs qualified installers",
     ["energy", "construction"], ["electrical_diagnosis", "installation_work"],
     "public infrastructure programs + vehicle electrification"),
    ("problem_energy_efficiency", "buildings and plants waste energy and pay for it",
     ["energy", "facilities", "manufacturing"], ["electrical_diagnosis", "systems_troubleshooting"],
     "energy cost pressure on operators"),
    ("problem_bookkeeping_burden", "small businesses drown in bookkeeping and compliance",
     ["financial_services", "retail"], ["bookkeeping", "tax_compliance", "business_administration"],
     "persistent SMB pain; automation tooling gap"),
    ("problem_trade_shortage", "skilled-trade shortage leaves demand unserved and training scarce",
     ["construction", "facilities"], ["training_delivery", "crew_supervision"],
     "aging trade workforce; apprenticeship gaps"),
    ("problem_fleet_maintenance", "fleets lose money to unplanned vehicle downtime",
     ["logistics", "automotive"], ["machinery_maintenance", "fleet_operations", "logistics_planning"],
     "uptime economics in delivery/logistics"),
    ("problem_patient_scheduling", "clinics lose capacity to scheduling and follow-up gaps",
     ["healthcare"], ["scheduling_dispatch", "business_administration", "patient_care"],
     "clinical operations pain"),
]

LICENSES = [
    ("occupation_unbify_elec", "*", "electrical license / certification (jurisdiction-specific)",
     ["independent electrical installation", "certification of work"]),
    ("occupation_unbify_plumber", "*", "plumbing license (jurisdiction-specific)",
     ["independent plumbing work"]),
    ("occupation_unbify_nurse", "*", "nursing registration", ["clinical practice"]),
    ("occupation_unbify_physician", "*", "medical license / registration",
     ["clinical practice", "prescribing"]),
    ("occupation_unbify_psychiatrist", "*", "medical license + psychiatry specialization",
     ["clinical practice", "prescribing", "psychiatric treatment"]),
    ("occupation_unbify_lawyer", "*", "bar admission / practicing certificate (jurisdiction-specific)",
     ["legal representation", "legal advice as practice"]),
    ("occupation_unbify_accountant", "*", "professional certification for audit/attestation work",
     ["statutory audit", "attestation"]),
    ("occupation_unbify_teacher", "*", "teaching qualification / registration (jurisdiction-specific)",
     ["school teaching"]),
    ("occupation_unbify_civileng", "*", "professional engineer registration for sign-off work",
     ["structural sign-off"]),
]

# baseline market observations (seed source: aggregated public labor statistics;
# real ingestion replaces/extends these through the same pipeline)
BASELINE_OBSERVATIONS = [
    # (occupation, signal_type, value, geography, source_quality_note)
    ("occupation_unbify_elec", "demand_direction", 0.6, "*"),
    ("occupation_unbify_elec", "self_employment_prevalence", 0.55, "*"),
    ("occupation_unbify_solar", "demand_direction", 0.75, "*"),
    ("occupation_unbify_plumber", "demand_direction", 0.55, "*"),
    ("occupation_unbify_carpenter", "demand_direction", 0.4, "*"),
    ("occupation_unbify_welder", "demand_direction", 0.35, "*"),
    ("occupation_unbify_mechanic", "demand_direction", 0.4, "*"),
    ("occupation_unbify_nurse", "demand_direction", 0.7, "*"),
    ("occupation_unbify_physician", "demand_direction", 0.6, "*"),
    ("occupation_unbify_psychiatrist", "demand_direction", 0.65, "*"),
    ("occupation_unbify_lawyer", "demand_direction", 0.3, "*"),
    ("occupation_unbify_accountant", "demand_direction", 0.35, "*"),
    ("occupation_unbify_teacher", "demand_direction", 0.45, "*"),
    ("occupation_unbify_civileng", "demand_direction", 0.5, "*"),
    ("occupation_unbify_mecheng", "demand_direction", 0.45, "*"),
    ("occupation_unbify_software", "demand_direction", 0.5, "*"),
    ("occupation_unbify_sales", "demand_direction", 0.45, "*"),
    ("occupation_unbify_supplychain", "demand_direction", 0.55, "*"),
    ("occupation_unbify_trainer", "demand_direction", 0.5, "*"),
    ("occupation_unbify_facilities", "demand_direction", 0.5, "*"),
    ("occupation_unbify_factoryop", "demand_direction", 0.2, "*"),
    ("occupation_unbify_farmer", "demand_direction", 0.3, "*"),
    ("occupation_unbify_shopowner", "demand_direction", 0.3, "*"),
]
