"""Curated interaction content catalog — data, not a question array.
Policy selects among eligible definitions; LLM-generated variants may join
after schema + business validation. Hidden option signals never leave the server."""

CATALOG_VERSION = "catalog_v1"

INTERACTIONS: list[dict] = [
    # ---------- Chapter 1 · grounded instinct (no projective symbolism) ----------
    {"id": "tt_freedom", "type": "binary_tension", "chapters": ["SELF_DISCOVERY"],
     "targets": ["autonomy", "stability"], "cognitive_cost": 0.2,
     "content": {"headline": "Two offers. Same money.", "supportingText": "One sets its own hours and its own problems. One has a plan and a boss. Drag to where you'd really land.",
                 "left": {"label": "Freedom", "dim": "autonomy"}, "right": {"label": "Certainty", "dim": "stability"}}},
    {"id": "tt_master", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["mastery", "exploration"], "cognitive_cost": 0.2,
     "content": {"headline": "Ten years in, someone describes you at a dinner.", "supportingText": "Are you the person they call for one specific thing — or the one who's done six different things well?",
                 "left": {"label": "Master one thing", "dim": "mastery"}, "right": {"label": "Keep discovering", "dim": "exploration"}}},
    {"id": "tt_build_sell", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "ALIGNMENT"],
     "targets": ["implementation_affinity", "sales_comfort"], "cognitive_cost": 0.2,
     "content": {"headline": "It's built. It works. Nobody's using it yet.", "supportingText": "Monday morning, you get one clear day. Where does it go?",
                 "left": {"label": "Build it better", "dim": "implementation_affinity"}, "right": {"label": "Get it into hands", "dim": "sales_comfort"}}},
    {"id": "tt_room", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["leadership", "facilitation"], "cognitive_cost": 0.2,
     "content": {"headline": "Twelve people, one decision, ninety minutes gone.", "supportingText": "It needs someone. Which someone are you?",
                 "left": {"label": "Lead the room", "dim": "leadership"}, "right": {"label": "Shape it quietly", "dim": "facilitation"}}},
    {"id": "tt_create", "type": "binary_tension", "chapters": ["SELF_DISCOVERY"],
     "targets": ["originality", "detail_orientation"], "cognitive_cost": 0.2,
     "content": {"headline": "Saturday, and the work is yours to pick.", "supportingText": "A blank page — or the thing that's 90% right and nagging at you.",
                 "left": {"label": "Create from nothing", "dim": "originality"}, "right": {"label": "Perfect what exists", "dim": "detail_orientation"}}},
    {"id": "sc_stuck", "type": "scenario_choice", "chapters": ["SELF_DISCOVERY"],
     "targets": ["systems_thinking", "leadership", "originality", "network"], "cognitive_cost": 0.3,
     "content": {"headline": "A project has completely stalled.", "supportingText": "What do you naturally do first?", "options": [
         {"id": "problem", "label": "Figure out what is actually wrong",
          "signals": [{"dim": "systems_thinking", "delta": .55, "weight": .5}, {"dim": "analytical", "delta": .4, "weight": .35}]},
         {"id": "moving", "label": "Get everyone moving again",
          "signals": [{"dim": "leadership", "delta": .55, "weight": .5}, {"dim": "initiative", "delta": .4, "weight": .35}]},
         {"id": "wild", "label": "Try something nobody considered",
          "signals": [{"dim": "originality", "delta": .55, "weight": .5}, {"dim": "experimentation", "delta": .45, "weight": .4}]},
         {"id": "person", "label": "Find someone who has solved this before",
          "signals": [{"dim": "network", "delta": .5, "weight": .45}, {"dim": "relationship_building", "delta": .4, "weight": .35}]},
     ]}},
    {"id": "fr_keep_two", "type": "forced_rank", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["autonomy", "mastery", "impact", "stability", "income_urgency"], "cognitive_cost": 0.4,
     "content": {"headline": "You can only keep two of these.", "supportingText": "The other four, you'd live without for the next few years.", "maxSelect": 2, "options": [
         {"id": "freedom", "label": "Freedom", "signals": [{"dim": "autonomy", "delta": .6, "weight": .55}]},
         {"id": "money", "label": "Money", "signals": [{"dim": "income_urgency", "delta": .5, "weight": .45}, {"dim": "revenue_ambition", "delta": .4, "weight": .35}]},
         {"id": "mastery", "label": "Mastery", "signals": [{"dim": "mastery", "delta": .6, "weight": .55}]},
         {"id": "impact", "label": "Impact", "signals": [{"dim": "impact", "delta": .6, "weight": .55}]},
         {"id": "stability", "label": "Stability", "signals": [{"dim": "stability", "delta": .6, "weight": .55}]},
         {"id": "recognition", "label": "Recognition", "signals": [{"dim": "reputation", "delta": .5, "weight": .45}]},
     ]}},
    {"id": "sc_free_month", "type": "scenario_choice", "chapters": ["SELF_DISCOVERY"],
     "targets": ["implementation_affinity", "mastery", "exploration", "stability"], "cognitive_cost": 0.25,
     "content": {"headline": "You unexpectedly get one completely free month.", "supportingText": "What sounds most tempting?", "options": [
         {"id": "build", "label": "Build something", "signals": [{"dim": "implementation_affinity", "delta": .55, "weight": .5}, {"dim": "initiative", "delta": .35, "weight": .3}]},
         {"id": "learn", "label": "Learn something deeply", "signals": [{"dim": "mastery", "delta": .55, "weight": .5}, {"dim": "analytical", "delta": .3, "weight": .25}]},
         {"id": "explore", "label": "Explore and meet people", "signals": [{"dim": "exploration", "delta": .5, "weight": .45}, {"dim": "relationship_building", "delta": .4, "weight": .35}]},
         {"id": "reset", "label": "Completely reset", "signals": [{"dim": "stability", "delta": .4, "weight": .35}, {"dim": "velocity", "delta": -.3, "weight": .25}]},
     ]}},
    {"id": "tt_frustrate", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["autonomy", "ambiguity_tolerance"], "cognitive_cost": 0.2,
     "content": {"headline": "Which of these would annoy you more, day to day?", "supportingText": None,
                 "left": {"label": "Someone controlling how I work", "dim": "autonomy"},
                 "right": {"label": "Not knowing where things are going", "dim": "ambiguity_tolerance", "dir": -1}}},
    {"id": "sc_messy_idea", "type": "scenario_choice", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["originality", "sales_comfort", "planning", "network"], "cognitive_cost": 0.3,
     "content": {"headline": "A good idea lands on the table. Nobody's running with it.", "supportingText": "What do you do first?", "options": [
         {"id": "shape", "label": "I start making it real", "signals": [{"dim": "implementation_affinity", "delta": .5, "weight": .45}, {"dim": "initiative", "delta": .4, "weight": .35}]},
         {"id": "test", "label": "I first work out whether anyone needs it", "signals": [{"dim": "sales_comfort", "delta": .5, "weight": .45}, {"dim": "experimentation", "delta": .4, "weight": .35}]},
         {"id": "people", "label": "I find the right people", "signals": [{"dim": "network", "delta": .5, "weight": .45}, {"dim": "facilitation", "delta": .35, "weight": .3}]},
         {"id": "worth", "label": "I figure out whether it's worth my time", "signals": [{"dim": "planning", "delta": .45, "weight": .4}, {"dim": "analytical", "delta": .4, "weight": .35}]},
     ]}},
    {"id": "sc_bigger_role", "type": "scenario_choice", "chapters": ["REFLECTION"],
     "targets": ["autonomy", "mastery", "stability"], "cognitive_cost": 0.3,
     "content": {"headline": "Your work is going well. Then someone offers a much bigger role — more money, much less control.",
                 "supportingText": "What bothers you first?", "options": [
         {"id": "control", "label": "Losing the freedom to decide", "signals": [{"dim": "autonomy", "delta": .55, "weight": .5}]},
         {"id": "machine", "label": "Being a small piece of something huge", "signals": [{"dim": "impact", "delta": .45, "weight": .4}, {"dim": "originality", "delta": .3, "weight": .25}]},
         {"id": "politics", "label": "Office politics replacing the actual work", "signals": [{"dim": "mastery", "delta": .5, "weight": .45}, {"dim": "facilitation", "delta": -.25, "weight": .2}]},
         {"id": "nothing", "label": "Honestly? Nothing — I'd take it", "signals": [{"dim": "stability", "delta": .45, "weight": .4}, {"dim": "revenue_ambition", "delta": .35, "weight": .3}]},
     ]}},
    {"id": "mr_six_months", "type": "micro_reflection", "chapters": ["REFLECTION"],
     "targets": ["autonomy", "purpose"], "cognitive_cost": 0.7,
     "content": {"headline": "Your income is covered for six months, starting Monday.",
                 "supportingText": "What would you actually change about how you work?",
                 "placeholder": "Honestly, I'd…", "help": "First thing that comes to mind. Nobody is grading this."}},
    {"id": "os_day", "type": "object_sort", "chapters": ["SELF_DISCOVERY"],
     "targets": ["mastery", "relationship_building", "originality", "sales_comfort", "leadership"], "cognitive_cost": 0.5,
     "content": {"headline": "Build a day you'd actually enjoy.", "supportingText": "Pick four pieces.", "maxSelect": 4, "options": [
         {"id": "deepwork", "label": "Deep work", "signals": [{"dim": "mastery", "delta": .4, "weight": .35}]},
         {"id": "people", "label": "People", "signals": [{"dim": "relationship_building", "delta": .4, "weight": .35}]},
         {"id": "movement", "label": "Movement", "signals": [{"dim": "velocity", "delta": .3, "weight": .25}]},
         {"id": "ideas", "label": "Ideas", "signals": [{"dim": "abstraction", "delta": .4, "weight": .35}]},
         {"id": "creating", "label": "Creating", "signals": [{"dim": "originality", "delta": .4, "weight": .35}]},
         {"id": "selling", "label": "Selling", "signals": [{"dim": "sales_comfort", "delta": .5, "weight": .45}]},
         {"id": "learning", "label": "Learning", "signals": [{"dim": "exploration", "delta": .35, "weight": .3}]},
         {"id": "leading", "label": "Leading", "signals": [{"dim": "leadership", "delta": .45, "weight": .4}]},
         {"id": "quiet", "label": "Quiet", "signals": [{"dim": "facilitation", "delta": -.3, "weight": .25}]},
         {"id": "competition", "label": "Competition", "signals": [{"dim": "risk_tolerance", "delta": .4, "weight": .35}]},
     ]}},
    # ---------- Chapter 2 · patterns ----------
    {"id": "sc_gift", "type": "scenario_choice", "chapters": ["REFLECTION"],
     "targets": ["implementation_affinity", "exploration", "relationship_building", "planning"], "cognitive_cost": 0.3,
     "content": {"headline": "A meeting gets cancelled. You have the afternoon.", "supportingText": "Be honest — what do you actually end up doing?", "options": [
         {"id": "make", "label": "Making something", "signals": [{"dim": "implementation_affinity", "delta": .5, "weight": .45}]},
         {"id": "learn", "label": "Reading about something unrelated", "signals": [{"dim": "exploration", "delta": .5, "weight": .45}]},
         {"id": "people", "label": "Calling someone you find interesting", "signals": [{"dim": "relationship_building", "delta": .5, "weight": .45}]},
         {"id": "order", "label": "Catching up on everything pending", "signals": [{"dim": "planning", "delta": .5, "weight": .45}]},
     ]}},
    {"id": "sc_praise", "type": "scenario_choice", "chapters": ["REFLECTION"],
     "targets": ["persistence", "originality", "persuasion", "initiative"], "cognitive_cost": 0.3,
     "content": {"headline": "Someone says one of these to you.", "supportingText": "Which one would you still be thinking about that evening?", "options": [
         {"id": "trusted", "label": "“I'd trust you with anything.”", "signals": [{"dim": "persistence", "delta": .45, "weight": .4}]},
         {"id": "seen", "label": "“Nobody thinks like you.”", "signals": [{"dim": "originality", "delta": .5, "weight": .45}]},
         {"id": "moved", "label": "“You changed how I see it.”", "signals": [{"dim": "persuasion", "delta": .45, "weight": .4}, {"dim": "teaching", "delta": .35, "weight": .3}]},
         {"id": "made", "label": "“You actually made it happen.”", "signals": [{"dim": "initiative", "delta": .45, "weight": .4}, {"dim": "velocity", "delta": .35, "weight": .3}]},
     ]}},
    {"id": "mr_repeated", "type": "micro_reflection", "chapters": ["REFLECTION"],
     "targets": ["domain_expertise", "pattern_recognition"], "cognitive_cost": 0.7,
     "content": {"headline": "One sentence, off the top of your head.", "supportingText": "What kind of problem do people keep bringing to you?",
                 "placeholder": "Somehow it's always…", "help": "Think of the last month. What kept landing on you?"}},
    {"id": "mr_smaller", "type": "micro_reflection", "chapters": ["REFLECTION"],
     "targets": ["purpose", "impact"], "cognitive_cost": 0.7,
     "content": {"headline": "Blunt one.", "supportingText": "What part of your work feels smaller than it should be by now?", "placeholder": "One honest line…"}},
    {"id": "mr_unusual", "type": "micro_reflection", "chapters": ["REFLECTION", "ALIGNMENT"],
     "targets": ["domain_expertise", "pattern_recognition"], "cognitive_cost": 0.7,
     "content": {"headline": "One more, then we're done.", "supportingText": "What do people thank you for that barely cost you anything?",
                 "placeholder": "It sounds small, but…", "help": "Not what you're proud of. What costs you the least effort."}},
    # ---------- Chapter 3 · reality ----------
    {"id": "al_status", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "current_status",
     "targets": ["stability", "exploration"], "cognitive_cost": 0.25, "bridge": "Let's make this real for a moment.",
     "content": {"headline": "What are you doing professionally right now?", "supportingText": "Broad strokes are fine.", "options": [
         {"id": "employed_good", "label": "Employed — and it mostly works", "signals": [{"dim": "stability", "delta": .2, "weight": .2}]},
         {"id": "employed_stale", "label": "Employed — but I've outgrown it", "signals": [{"dim": "exploration", "delta": .3, "weight": .25}]},
         {"id": "founder", "label": "Founder / business owner", "signals": [{"dim": "risk_tolerance", "delta": .35, "weight": .3}, {"dim": "initiative", "delta": .3, "weight": .25}]},
         {"id": "freelance", "label": "Freelance / consulting", "signals": [{"dim": "autonomy", "delta": .35, "weight": .3}]},
         {"id": "student", "label": "Studying", "signals": []},
         {"id": "between", "label": "Between jobs", "signals": [{"dim": "ambiguity_tolerance", "delta": .2, "weight": .15}]},
     ]}},
    {"id": "mr_pro_what", "type": "micro_reflection", "chapters": ["ALIGNMENT"], "practical_key": "profession_text",
     "targets": ["domain_expertise"], "cognitive_cost": 0.6, "extract": "professional",
     "content": {"headline": "What do you actually do?", "supportingText": "Don't worry about the job title. One sentence is enough.",
                 "placeholder": "e.g. I manage logistics for a food company and fix broken processes",
                 "help": "Describe a normal week to a friend, not a recruiter."}},
    {"id": "sp_years", "type": "spectrum", "chapters": ["ALIGNMENT"], "practical_key": "years_experience",
     "requires_status": ["employed", "founder", "freelance"],
     "targets": ["domain_expertise"], "cognitive_cost": 0.2,
     "content": {"headline": "How long have you worked in this line of work?", "supportingText": None,
                 "left": {"label": "Just starting", "dim": "domain_expertise", "dir": -1},
                 "right": {"label": "Many years in", "dim": "domain_expertise", "dir": 1}}},
    {"id": "sc_problem_money", "type": "scenario_choice", "chapters": ["ALIGNMENT"],
     "targets": ["initiative", "sales_comfort", "stability", "network"], "cognitive_cost": 0.3,
     "bridge": "This one matters more than it looks.",
     "content": {"headline": "You spot something your industry keeps wasting money on.",
                 "supportingText": "What's your honest first reaction?", "options": [
         {"id": "solve", "label": "I'd probably start solving it myself", "signals": [{"dim": "initiative", "delta": .55, "weight": .5}, {"dim": "implementation_affinity", "delta": .4, "weight": .35}]},
         {"id": "pay", "label": "I'd want to know who would actually pay first", "signals": [{"dim": "sales_comfort", "delta": .55, "weight": .5}, {"dim": "analytical", "delta": .3, "weight": .25}]},
         {"id": "company", "label": "I'd bring it to the company I'm already in", "signals": [{"dim": "stability", "delta": .45, "weight": .4}, {"dim": "planning", "delta": .3, "weight": .25}]},
         {"id": "move_on", "label": "I'd notice it but probably keep moving", "signals": [{"dim": "risk_tolerance", "delta": -.35, "weight": .3}]},
     ]}},
    {"id": "tt_fail_untested", "type": "binary_tension", "chapters": ["ALIGNMENT"],
     "targets": ["risk_tolerance", "purpose"], "cognitive_cost": 0.25,
     "content": {"headline": "Which sounds harder to tolerate?", "supportingText": None,
                 "left": {"label": "Building something that might fail", "dim": "risk_tolerance", "dir": -1},
                 "right": {"label": "Never testing something you believed in", "dim": "risk_tolerance", "dir": 1}}},
    {"id": "sc_tried_earning", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "entrepreneurial_history",
     "targets": ["revenue_ambition", "initiative"], "cognitive_cost": 0.25,
     "bridge": "There's one thing I'd rather not guess.",
     "content": {"headline": "Have you ever seriously tried to earn money from something of your own?", "supportingText": None, "options": [
         {"id": "already", "label": "Yes — I already do", "signals": [{"dim": "revenue_ambition", "delta": .5, "weight": .45}, {"dim": "sales_comfort", "delta": .4, "weight": .35}]},
         {"id": "tried", "label": "I tried before", "signals": [{"dim": "initiative", "delta": .4, "weight": .35}, {"dim": "experimentation", "delta": .35, "weight": .3}]},
         {"id": "experimenting", "label": "I'm experimenting now", "signals": [{"dim": "experimentation", "delta": .5, "weight": .45}, {"dim": "initiative", "delta": .35, "weight": .3}]},
         {"id": "thought", "label": "I've thought about it seriously", "signals": [{"dim": "revenue_ambition", "delta": .25, "weight": .2}]},
         {"id": "not_really", "label": "Not really", "signals": [{"dim": "risk_tolerance", "delta": -.2, "weight": .2}]},
     ]}},
    # ---- status-dependent branches: never ask an employee founder questions ----
    {"id": "sc_biz_stage", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "business_stage",
     "requires_status": ["founder"], "targets": ["revenue_ambition"], "cognitive_cost": 0.25,
     "content": {"headline": "The thing you're building — how far along is it?", "supportingText": None, "options": [
         {"id": "idea", "label": "Still an idea taking shape", "signals": [{"dim": "experimentation", "delta": .3, "weight": .25}]},
         {"id": "building", "label": "Being built", "signals": [{"dim": "implementation_affinity", "delta": .4, "weight": .35}]},
         {"id": "first_customers", "label": "First customers", "signals": [{"dim": "sales_comfort", "delta": .45, "weight": .4}]},
         {"id": "revenue", "label": "Real revenue", "signals": [{"dim": "revenue_ambition", "delta": .5, "weight": .45}]},
     ]}},
    {"id": "sc_own_scope", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "ownership_scope",
     "requires_status": ["employed"], "targets": ["leadership", "planning"], "cognitive_cost": 0.25,
     "content": {"headline": "In your current role — what do you actually own?", "supportingText": "Not the title. The reality.", "options": [
         {"id": "tasks", "label": "My tasks, mostly", "signals": [{"dim": "leadership", "delta": -.2, "weight": .2}]},
         {"id": "area", "label": "A whole area", "signals": [{"dim": "planning", "delta": .4, "weight": .35}]},
         {"id": "outcomes", "label": "Outcomes, people, budget", "signals": [{"dim": "leadership", "delta": .5, "weight": .45}]},
         {"id": "little", "label": "Almost nothing — and it shows", "signals": [{"dim": "autonomy", "delta": .35, "weight": .3}, {"dim": "impact", "delta": .3, "weight": .25}]},
     ]}},
    {"id": "sc_student_real", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "student_experience",
     "requires_status": ["student"], "targets": ["implementation_affinity", "initiative"], "cognitive_cost": 0.25,
     "content": {"headline": "The most real thing you've done outside class?", "supportingText": None, "options": [
         {"id": "shipped", "label": "Built or shipped something", "signals": [{"dim": "implementation_affinity", "delta": .5, "weight": .45}]},
         {"id": "worked", "label": "Worked or interned properly", "signals": [{"dim": "persistence", "delta": .35, "weight": .3}]},
         {"id": "organized", "label": "Organized people around something", "signals": [{"dim": "facilitation", "delta": .45, "weight": .4}, {"dim": "leadership", "delta": .35, "weight": .3}]},
         {"id": "studying", "label": "Mostly studied, honestly", "signals": [{"dim": "planning", "delta": .2, "weight": .2}]},
     ]}},
    {"id": "al_hours", "type": "spectrum", "chapters": ["ALIGNMENT"], "practical_key": "hours_per_week",
     "targets": ["time_availability"], "cognitive_cost": 0.2,
     "content": {"headline": "Honestly — how much time could you give something new?", "supportingText": "Not ideally. Actually.",
                 "left": {"label": "A few odd hours", "dim": "time_availability", "dir": -1}, "right": {"label": "Real, serious time", "dim": "time_availability", "dir": 1}}},
    {"id": "al_money", "type": "spectrum", "chapters": ["ALIGNMENT"], "practical_key": "money_pressure",
     "targets": ["income_urgency"], "cognitive_cost": 0.2,
     "content": {"headline": "And money — how tight is it right now?", "supportingText": "This changes what's sensible, not what's possible.",
                 "left": {"label": "No rush for money", "dim": "income_urgency", "dir": -1}, "right": {"label": "Real pressure", "dim": "income_urgency", "dir": 1}}},
    {"id": "al_risk", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "risk_appetite",
     "targets": ["risk_tolerance", "planning"], "cognitive_cost": 0.3,
     "content": {"headline": "A real opportunity, with a real chance of losing money.", "supportingText": "What do you actually do?", "options": [
         {"id": "walk", "label": "Walk through it", "signals": [{"dim": "risk_tolerance", "delta": .55, "weight": .5}]},
         {"id": "test", "label": "Test it from the doorway", "signals": [{"dim": "experimentation", "delta": .45, "weight": .4}]},
         {"id": "prepare", "label": "Prepare, then decide", "signals": [{"dim": "planning", "delta": .45, "weight": .4}, {"dim": "risk_tolerance", "delta": -.2, "weight": .2}]},
         {"id": "hold", "label": "Not this season", "signals": [{"dim": "risk_tolerance", "delta": -.45, "weight": .4}, {"dim": "stability", "delta": .3, "weight": .25}]},
     ]}},
    {"id": "al_assets", "type": "object_sort", "chapters": ["ALIGNMENT"], "practical_key": "assets",
     "targets": ["domain_expertise", "network", "audience", "capital_availability", "ai_leverage"], "cognitive_cost": 0.45,
     "content": {"headline": "What have you already got?", "supportingText": "Tick everything that's true for you.", "maxSelect": 8, "minSelect": 1, "options": [
         {"id": "deep_field", "label": "Deep knowledge of a field", "signals": [{"dim": "domain_expertise", "delta": .6, "weight": .55}]},
         {"id": "network", "label": "People who'd take my call", "signals": [{"dim": "network", "delta": .55, "weight": .5}]},
         {"id": "audience", "label": "An audience, even small", "signals": [{"dim": "audience", "delta": .55, "weight": .5}]},
         {"id": "credentials", "label": "Credentials that open doors", "signals": [{"dim": "credentials", "delta": .5, "weight": .45}]},
         {"id": "savings", "label": "A financial cushion", "signals": [{"dim": "capital_availability", "delta": .55, "weight": .5}]},
         {"id": "craft", "label": "A craft people pay for", "signals": [{"dim": "implementation_affinity", "delta": .45, "weight": .4}]},
         {"id": "reputation", "label": "A good name where it counts", "signals": [{"dim": "reputation", "delta": .5, "weight": .45}]},
         {"id": "tools", "label": "Comfort with new AI tools", "signals": [{"dim": "ai_leverage", "delta": .55, "weight": .5}, {"dim": "adaptability", "delta": .35, "weight": .3}]},
     ]}},
    {"id": "al_geo", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "geography",
     "targets": ["geographic_access"], "cognitive_cost": 0.2,
     "content": {"headline": "Where do you actually live and work?", "supportingText": None, "options": [
         {"id": "anchored", "label": "Anchored to one place", "signals": [{"dim": "geographic_access", "delta": -.2, "weight": .2}]},
         {"id": "hub", "label": "In or near a major hub", "signals": [{"dim": "geographic_access", "delta": .5, "weight": .45}]},
         {"id": "flexible", "label": "Genuinely flexible", "signals": [{"dim": "adaptability", "delta": .3, "weight": .25}]},
         {"id": "online", "label": "Mostly online anyway", "signals": [{"dim": "ai_leverage", "delta": .25, "weight": .2}]},
     ]}},
    {"id": "al_solo", "type": "binary_tension", "chapters": ["ALIGNMENT"], "practical_key": "solo_or_team",
     "targets": ["facilitation"], "cognitive_cost": 0.2,
     "content": {"headline": "You do your best work…", "supportingText": None,
                 "left": {"label": "On your own, uninterrupted", "dim": "facilitation", "dir": -1}, "right": {"label": "With a couple of other people", "dim": "facilitation", "dir": 1}}},
]

MOTIFS = ["mountain", "sea", "city", "library", "workshop", "stage", "garden", "market", "studio", "night", "path", "harbor"]
