"""Curated interaction content catalog — data, not a question array.
Policy selects among eligible definitions; LLM-generated variants may join
after schema + business validation. Hidden option signals never leave the server."""

CATALOG_VERSION = "catalog_v1"

INTERACTIONS: list[dict] = [
    # ---------- Chapter 1 · grounded instinct (no projective symbolism) ----------
    {"id": "tt_freedom", "type": "binary_tension", "chapters": ["SELF_DISCOVERY"],
     "targets": ["autonomy", "stability"], "cognitive_cost": 0.2,
     "content": {"headline": "Somewhere between these is you.", "supportingText": "Drag to where you actually live.",
                 "left": {"label": "Freedom", "dim": "autonomy"}, "right": {"label": "Certainty", "dim": "stability"}}},
    {"id": "tt_master", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["mastery", "exploration"], "cognitive_cost": 0.2,
     "content": {"headline": "Ten years from now.", "supportingText": "Which side would you rather be on?",
                 "left": {"label": "Master one thing", "dim": "mastery"}, "right": {"label": "Keep discovering", "dim": "exploration"}}},
    {"id": "tt_build_sell", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "ALIGNMENT"],
     "targets": ["implementation_affinity", "sales_comfort"], "cognitive_cost": 0.2,
     "content": {"headline": "The thing exists. Now what?", "supportingText": None,
                 "left": {"label": "Build it better", "dim": "implementation_affinity"}, "right": {"label": "Get it into hands", "dim": "sales_comfort"}}},
    {"id": "tt_room", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["leadership", "facilitation"], "cognitive_cost": 0.2,
     "content": {"headline": "The room is full. The decision is big.", "supportingText": None,
                 "left": {"label": "Lead the room", "dim": "leadership"}, "right": {"label": "Shape it quietly", "dim": "facilitation"}}},
    {"id": "tt_create", "type": "binary_tension", "chapters": ["SELF_DISCOVERY"],
     "targets": ["originality", "detail_orientation"], "cognitive_cost": 0.2,
     "content": {"headline": "Given the choice:", "supportingText": None,
                 "left": {"label": "Create from nothing", "dim": "originality"}, "right": {"label": "Perfect what exists", "dim": "detail_orientation"}}},
    {"id": "sc_stuck", "type": "scenario_choice", "chapters": ["SELF_DISCOVERY"],
     "targets": ["systems_thinking", "leadership", "originality", "network"], "cognitive_cost": 0.3,
     "content": {"headline": "A project has completely stalled.", "supportingText": "What do you naturally do first?", "options": [
         {"id": "problem", "label": "Figure out what is actually wrong",
          "signals": [{"dim": "systems_thinking", "delta": .55, "weight": .5}, {"dim": "analytical", "delta": .4, "weight": .35}]},
         {"id": "moving", "label": "Get everyone moving again",
          "signals": [{"dim": "leadership", "delta": .55, "weight": .5}, {"dim": "initiative", "delta": .4, "weight": .35}]},
         {"id": "wild", "label": "Try something nobody considered",
          "signals": [{"dim": "originality", "delta": .55, "weight": .5}, {"dim": "experimentation", "delta": .45, "weight": .4}]},
         {"id": "person", "label": "Find someone who has solved this before",
          "signals": [{"dim": "network", "delta": .5, "weight": .45}, {"dim": "relationship_building", "delta": .4, "weight": .35}]},
     ]}},
    {"id": "fr_keep_two", "type": "forced_rank", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["autonomy", "mastery", "impact", "stability", "income_urgency"], "cognitive_cost": 0.4,
     "content": {"headline": "Keep only two.", "supportingText": "The rest you can live without — for now.", "maxSelect": 2, "options": [
         {"id": "freedom", "label": "Freedom", "signals": [{"dim": "autonomy", "delta": .6, "weight": .55}]},
         {"id": "money", "label": "Money", "signals": [{"dim": "income_urgency", "delta": .5, "weight": .45}, {"dim": "revenue_ambition", "delta": .4, "weight": .35}]},
         {"id": "mastery", "label": "Mastery", "signals": [{"dim": "mastery", "delta": .6, "weight": .55}]},
         {"id": "impact", "label": "Impact", "signals": [{"dim": "impact", "delta": .6, "weight": .55}]},
         {"id": "stability", "label": "Stability", "signals": [{"dim": "stability", "delta": .6, "weight": .55}]},
         {"id": "recognition", "label": "Recognition", "signals": [{"dim": "reputation", "delta": .5, "weight": .45}]},
     ]}},
    {"id": "sc_free_month", "type": "scenario_choice", "chapters": ["SELF_DISCOVERY"],
     "targets": ["implementation_affinity", "mastery", "exploration", "stability"], "cognitive_cost": 0.25,
     "content": {"headline": "You unexpectedly get one completely free month.", "supportingText": "What sounds most tempting?", "options": [
         {"id": "build", "label": "Build something", "signals": [{"dim": "implementation_affinity", "delta": .55, "weight": .5}, {"dim": "initiative", "delta": .35, "weight": .3}]},
         {"id": "learn", "label": "Learn something deeply", "signals": [{"dim": "mastery", "delta": .55, "weight": .5}, {"dim": "analytical", "delta": .3, "weight": .25}]},
         {"id": "explore", "label": "Explore and meet people", "signals": [{"dim": "exploration", "delta": .5, "weight": .45}, {"dim": "relationship_building", "delta": .4, "weight": .35}]},
         {"id": "reset", "label": "Completely reset", "signals": [{"dim": "stability", "delta": .4, "weight": .35}, {"dim": "velocity", "delta": -.3, "weight": .25}]},
     ]}},
    {"id": "tt_frustrate", "type": "binary_tension", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["autonomy", "ambiguity_tolerance"], "cognitive_cost": 0.2,
     "content": {"headline": "Which would frustrate you more?", "supportingText": None,
                 "left": {"label": "Someone controlling how I work", "dim": "autonomy"},
                 "right": {"label": "Not knowing where things are going", "dim": "ambiguity_tolerance", "dir": -1}}},
    {"id": "sc_messy_idea", "type": "scenario_choice", "chapters": ["SELF_DISCOVERY", "REFLECTION"],
     "targets": ["originality", "sales_comfort", "planning", "network"], "cognitive_cost": 0.3,
     "content": {"headline": "Someone gives you a messy idea with huge potential.", "supportingText": "What happens naturally?", "options": [
         {"id": "shape", "label": "I start shaping it", "signals": [{"dim": "originality", "delta": .5, "weight": .45}, {"dim": "synthesis", "delta": .4, "weight": .35}]},
         {"id": "test", "label": "I test whether anyone wants it", "signals": [{"dim": "sales_comfort", "delta": .5, "weight": .45}, {"dim": "experimentation", "delta": .4, "weight": .35}]},
         {"id": "organize", "label": "I organize how it could actually work", "signals": [{"dim": "planning", "delta": .5, "weight": .45}, {"dim": "systems_thinking", "delta": .4, "weight": .35}]},
         {"id": "people", "label": "I start finding the right people", "signals": [{"dim": "network", "delta": .5, "weight": .45}, {"dim": "facilitation", "delta": .35, "weight": .3}]},
     ]}},
    {"id": "os_day", "type": "object_sort", "chapters": ["SELF_DISCOVERY"],
     "targets": ["mastery", "relationship_building", "originality", "sales_comfort", "leadership"], "cognitive_cost": 0.5,
     "content": {"headline": "Build a day you'd actually enjoy.", "supportingText": "Pick four pieces.", "maxSelect": 4, "options": [
         {"id": "deepwork", "label": "Deep work", "signals": [{"dim": "mastery", "delta": .4, "weight": .35}]},
         {"id": "people", "label": "People", "signals": [{"dim": "relationship_building", "delta": .4, "weight": .35}]},
         {"id": "movement", "label": "Movement", "signals": [{"dim": "velocity", "delta": .3, "weight": .25}]},
         {"id": "ideas", "label": "Ideas", "signals": [{"dim": "abstraction", "delta": .4, "weight": .35}]},
         {"id": "creating", "label": "Creating", "signals": [{"dim": "originality", "delta": .4, "weight": .35}]},
         {"id": "selling", "label": "Selling", "signals": [{"dim": "sales_comfort", "delta": .5, "weight": .45}]},
         {"id": "learning", "label": "Learning", "signals": [{"dim": "exploration", "delta": .35, "weight": .3}]},
         {"id": "leading", "label": "Leading", "signals": [{"dim": "leadership", "delta": .45, "weight": .4}]},
         {"id": "quiet", "label": "Quiet", "signals": [{"dim": "facilitation", "delta": -.3, "weight": .25}]},
         {"id": "competition", "label": "Competition", "signals": [{"dim": "risk_tolerance", "delta": .4, "weight": .35}]},
     ]}},
    # ---------- Chapter 2 · patterns ----------
    {"id": "sc_gift", "type": "scenario_choice", "chapters": ["REFLECTION"],
     "targets": ["implementation_affinity", "exploration", "relationship_building", "planning"], "cognitive_cost": 0.3,
     "content": {"headline": "A free afternoon appears out of nowhere.", "supportingText": "Honestly — where does it go?", "options": [
         {"id": "make", "label": "Making something", "signals": [{"dim": "implementation_affinity", "delta": .5, "weight": .45}]},
         {"id": "learn", "label": "Falling down a rabbit hole", "signals": [{"dim": "exploration", "delta": .5, "weight": .45}]},
         {"id": "people", "label": "Calling someone interesting", "signals": [{"dim": "relationship_building", "delta": .5, "weight": .45}]},
         {"id": "order", "label": "Clearing the decks", "signals": [{"dim": "planning", "delta": .5, "weight": .45}]},
     ]}},
    {"id": "sc_praise", "type": "scenario_choice", "chapters": ["REFLECTION"],
     "targets": ["persistence", "originality", "persuasion", "initiative"], "cognitive_cost": 0.3,
     "content": {"headline": "Which compliment lands deepest?", "supportingText": "Not which one you'd say — which one you'd feel.", "options": [
         {"id": "trusted", "label": "“I'd trust you with anything.”", "signals": [{"dim": "persistence", "delta": .45, "weight": .4}]},
         {"id": "seen", "label": "“Nobody thinks like you.”", "signals": [{"dim": "originality", "delta": .5, "weight": .45}]},
         {"id": "moved", "label": "“You changed how I see it.”", "signals": [{"dim": "persuasion", "delta": .45, "weight": .4}, {"dim": "teaching", "delta": .35, "weight": .3}]},
         {"id": "made", "label": "“You actually made it happen.”", "signals": [{"dim": "initiative", "delta": .45, "weight": .4}, {"dim": "velocity", "delta": .35, "weight": .3}]},
     ]}},
    {"id": "mr_cometo", "type": "micro_reflection", "chapters": ["REFLECTION"],
     "targets": ["domain_expertise", "teaching"], "cognitive_cost": 0.7,
     "content": {"headline": "One sentence.", "supportingText": "What do people naturally come to you for?", "placeholder": "They come to me when…"}},
    {"id": "mr_smaller", "type": "micro_reflection", "chapters": ["REFLECTION"],
     "targets": ["purpose", "impact"], "cognitive_cost": 0.7,
     "content": {"headline": "Finish this quietly.", "supportingText": "What part of your life feels smaller than it should?", "placeholder": "One honest line…"}},
    {"id": "mr_unusual", "type": "micro_reflection", "chapters": ["REFLECTION", "ALIGNMENT"],
     "targets": ["domain_expertise", "pattern_recognition"], "cognitive_cost": 0.7,
     "content": {"headline": "Almost done noticing.", "supportingText": "What are you unusually good at that you rarely think about?", "placeholder": "It sounds small, but…"}},
    # ---------- Chapter 3 · reality ----------
    {"id": "al_work", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "career_stage",
     "targets": ["stability", "exploration"], "cognitive_cost": 0.25,
     "content": {"headline": "Let's put this version of you into the real world.", "supportingText": "Right now, work looks like…", "options": [
         {"id": "employed_good", "label": "A role that mostly works", "signals": [{"dim": "stability", "delta": .2, "weight": .2}]},
         {"id": "employed_stale", "label": "A role I've outgrown", "signals": [{"dim": "exploration", "delta": .3, "weight": .25}]},
         {"id": "independent", "label": "Already independent", "signals": [{"dim": "autonomy", "delta": .35, "weight": .3}, {"dim": "risk_tolerance", "delta": .25, "weight": .2}]},
         {"id": "between", "label": "Between chapters", "signals": [{"dim": "ambiguity_tolerance", "delta": .2, "weight": .15}]},
         {"id": "studying", "label": "Still studying", "signals": []},
     ]}},
    {"id": "al_hours", "type": "spectrum", "chapters": ["ALIGNMENT"], "practical_key": "hours_per_week",
     "targets": ["time_availability"], "cognitive_cost": 0.2,
     "content": {"headline": "Honestly — how much time could you give something new?", "supportingText": "Not ideally. Actually.",
                 "left": {"label": "Stolen hours", "dim": "time_availability", "dir": -1}, "right": {"label": "Real, serious time", "dim": "time_availability", "dir": 1}}},
    {"id": "al_money", "type": "spectrum", "chapters": ["ALIGNMENT"], "practical_key": "money_pressure",
     "targets": ["income_urgency"], "cognitive_cost": 0.2,
     "content": {"headline": "And money, right now?", "supportingText": "This changes what's wise — not what's possible.",
                 "left": {"label": "Breathing room", "dim": "income_urgency", "dir": -1}, "right": {"label": "Real pressure", "dim": "income_urgency", "dir": 1}}},
    {"id": "al_risk", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "risk_appetite",
     "targets": ["risk_tolerance", "planning"], "cognitive_cost": 0.3,
     "content": {"headline": "A door opens. Good odds, real downside.", "supportingText": "Your honest move:", "options": [
         {"id": "walk", "label": "Walk through it", "signals": [{"dim": "risk_tolerance", "delta": .55, "weight": .5}]},
         {"id": "test", "label": "Test it from the doorway", "signals": [{"dim": "experimentation", "delta": .45, "weight": .4}]},
         {"id": "prepare", "label": "Prepare, then decide", "signals": [{"dim": "planning", "delta": .45, "weight": .4}, {"dim": "risk_tolerance", "delta": -.2, "weight": .2}]},
         {"id": "hold", "label": "Not this season", "signals": [{"dim": "risk_tolerance", "delta": -.45, "weight": .4}, {"dim": "stability", "delta": .3, "weight": .25}]},
     ]}},
    {"id": "al_assets", "type": "object_sort", "chapters": ["ALIGNMENT"], "practical_key": "assets",
     "targets": ["domain_expertise", "network", "audience", "capital_availability", "ai_leverage"], "cognitive_cost": 0.45,
     "content": {"headline": "What do you already carry?", "supportingText": "Pick everything that's true.", "maxSelect": 8, "minSelect": 1, "options": [
         {"id": "deep_field", "label": "Deep knowledge of a field", "signals": [{"dim": "domain_expertise", "delta": .6, "weight": .55}]},
         {"id": "network", "label": "People who'd take my call", "signals": [{"dim": "network", "delta": .55, "weight": .5}]},
         {"id": "audience", "label": "An audience, even small", "signals": [{"dim": "audience", "delta": .55, "weight": .5}]},
         {"id": "credentials", "label": "Credentials that open doors", "signals": [{"dim": "credentials", "delta": .5, "weight": .45}]},
         {"id": "savings", "label": "A financial cushion", "signals": [{"dim": "capital_availability", "delta": .55, "weight": .5}]},
         {"id": "craft", "label": "A craft people pay for", "signals": [{"dim": "implementation_affinity", "delta": .45, "weight": .4}]},
         {"id": "reputation", "label": "A good name where it counts", "signals": [{"dim": "reputation", "delta": .5, "weight": .45}]},
         {"id": "tools", "label": "Comfort with new AI tools", "signals": [{"dim": "ai_leverage", "delta": .55, "weight": .5}, {"dim": "adaptability", "delta": .35, "weight": .3}]},
     ]}},
    {"id": "al_geo", "type": "scenario_choice", "chapters": ["ALIGNMENT"], "practical_key": "geography",
     "targets": ["geographic_access"], "cognitive_cost": 0.2,
     "content": {"headline": "Where does your life actually happen?", "supportingText": None, "options": [
         {"id": "anchored", "label": "Anchored to one place", "signals": [{"dim": "geographic_access", "delta": -.2, "weight": .2}]},
         {"id": "hub", "label": "In or near a major hub", "signals": [{"dim": "geographic_access", "delta": .5, "weight": .45}]},
         {"id": "flexible", "label": "Genuinely flexible", "signals": [{"dim": "adaptability", "delta": .3, "weight": .25}]},
         {"id": "online", "label": "Mostly online anyway", "signals": [{"dim": "ai_leverage", "delta": .25, "weight": .2}]},
     ]}},
    {"id": "al_solo", "type": "binary_tension", "chapters": ["ALIGNMENT"], "practical_key": "solo_or_team",
     "targets": ["facilitation"], "cognitive_cost": 0.2,
     "content": {"headline": "Your best work tends to happen…", "supportingText": None,
                 "left": {"label": "Alone, deep", "dim": "facilitation", "dir": -1}, "right": {"label": "With a small crew", "dim": "facilitation", "dir": 1}}},
]

MOTIFS = ["mountain", "sea", "city", "library", "workshop", "stage", "garden", "market", "studio", "night", "path", "harbor"]
