"""initial schema

Revision ID: f11446d6b359
Revises: 
Create Date: 2026-08-18 22:46:30.974288
"""
from alembic import op
import sqlalchemy as sa


revision = 'f11446d6b359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=60), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_assignments_experiment_id'), 'experiment_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_session_id'), 'experiment_assignments', ['session_id'], unique=False)
    op.create_index('uq_exp_session', 'experiment_assignments', ['experiment_id', 'session_id'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_snapshots_session_id'), 'feature_snapshots', ['session_id'], unique=False)
    op.create_table('interaction_definitions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('chapters', sa.JSON(), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('cognitive_cost', sa.Float(), nullable=False),
    sa.Column('practical_key', sa.String(length=40), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('family', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('artifact_uri', sa.String(length=400), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('dataset_ref', sa.String(length=120), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('pathway_type', sa.String(length=30), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value_proposition', sa.Text(), nullable=False),
    sa.Column('prerequisite_features', sa.JSON(), nullable=False),
    sa.Column('preferred_features', sa.JSON(), nullable=False),
    sa.Column('disqualifiers', sa.JSON(), nullable=False),
    sa.Column('skill_gaps', sa.JSON(), nullable=False),
    sa.Column('startup_capital', sa.String(length=30), nullable=False),
    sa.Column('time_to_first_value', sa.String(length=30), nullable=False),
    sa.Column('income_range', sa.String(length=60), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=False),
    sa.Column('ai_leverage_score', sa.Float(), nullable=False),
    sa.Column('human_differentiation_score', sa.Float(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('evidence_sources', sa.JSON(), nullable=False),
    sa.Column('related_products', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('freshness_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('opportunity_id', sa.String(length=60), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_session_id'), 'outcomes', ['session_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadow_predictions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('production_value', sa.JSON(), nullable=False),
    sa.Column('shadow_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_predictions_model_id'), 'shadow_predictions', ['model_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('anonymous_identities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('anon_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anon_id'], ['anonymous_identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discover_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('anon_id', sa.String(length=32), nullable=False),
    sa.Column('journey_status', sa.String(length=30), nullable=False),
    sa.Column('chapter_progress', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('contradictions', sa.JSON(), nullable=False),
    sa.Column('practical_context', sa.JSON(), nullable=False),
    sa.Column('revealed_insights', sa.JSON(), nullable=False),
    sa.Column('recent_interaction_types', sa.JSON(), nullable=False),
    sa.Column('counters', sa.JSON(), nullable=False),
    sa.Column('engagement', sa.JSON(), nullable=False),
    sa.Column('used_definitions', sa.JSON(), nullable=False),
    sa.Column('pending_instance_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anon_id'], ['anonymous_identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('reveal_id', sa.String(length=32), nullable=True),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_feedback_session_id'), 'calibration_feedback', ['session_id'], unique=False)
    op.create_table('interaction_instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('definition_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('chapter', sa.String(length=30), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('public_content', sa.JSON(), nullable=False),
    sa.Column('policy_decision_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_instances_session_id'), 'interaction_instances', ['session_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('eligible_actions', sa.JSON(), nullable=False),
    sa.Column('chosen_action', sa.String(length=60), nullable=False),
    sa.Column('propensity', sa.Float(), nullable=False),
    sa.Column('action_values', sa.JSON(), nullable=False),
    sa.Column('reward_components', sa.JSON(), nullable=False),
    sa.Column('reward_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_session_id'), 'policy_decisions', ['session_id'], unique=False)
    op.create_table('profile_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('checkpoint', sa.String(length=40), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('contradictions', sa.JSON(), nullable=False),
    sa.Column('corrections', sa.JSON(), nullable=False),
    sa.Column('practical_context', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('signal_version', sa.String(length=20), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_versions_session_id'), 'profile_versions', ['session_id'], unique=False)
    op.create_table('recommendation_sets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('profile_version_id', sa.String(length=32), nullable=True),
    sa.Column('ranking_model', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_sets_session_id'), 'recommendation_sets', ['session_id'], unique=False)
    op.create_table('reveals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('insight', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reveals_session_id'), 'reveals', ['session_id'], unique=False)
    op.create_table('signal_evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=True),
    sa.Column('response_id', sa.String(length=32), nullable=True),
    sa.Column('construct_updates', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('signal_version', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_evidence_session_id'), 'signal_evidence', ['session_id'], unique=False)
    op.create_table('user_corrections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('insight_summary', sa.Text(), nullable=False),
    sa.Column('dims', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_corrections_session_id'), 'user_corrections', ['session_id'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=60), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('factor_contributions', sa.JSON(), nullable=False),
    sa.Column('narrative', sa.JSON(), nullable=False),
    sa.Column('explored', sa.Boolean(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['recommendation_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_items_set_id'), 'recommendation_items', ['set_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['interaction_instances.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['discover_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id')
    )
    op.create_index(op.f('ix_responses_session_id'), 'responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_session_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_recommendation_items_set_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_user_corrections_session_id'), table_name='user_corrections')
    op.drop_table('user_corrections')
    op.drop_index(op.f('ix_signal_evidence_session_id'), table_name='signal_evidence')
    op.drop_table('signal_evidence')
    op.drop_index(op.f('ix_reveals_session_id'), table_name='reveals')
    op.drop_table('reveals')
    op.drop_index(op.f('ix_recommendation_sets_session_id'), table_name='recommendation_sets')
    op.drop_table('recommendation_sets')
    op.drop_index(op.f('ix_profile_versions_session_id'), table_name='profile_versions')
    op.drop_table('profile_versions')
    op.drop_index(op.f('ix_policy_decisions_session_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_interaction_instances_session_id'), table_name='interaction_instances')
    op.drop_table('interaction_instances')
    op.drop_index(op.f('ix_calibration_feedback_session_id'), table_name='calibration_feedback')
    op.drop_table('calibration_feedback')
    op.drop_table('discover_sessions')
    op.drop_table('consents')
    op.drop_table('anonymous_identities')
    op.drop_table('users')
    op.drop_index(op.f('ix_shadow_predictions_model_id'), table_name='shadow_predictions')
    op.drop_table('shadow_predictions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_outcomes_session_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_table('opportunities')
    op.drop_table('model_registry')
    op.drop_table('llm_calls')
    op.drop_table('interaction_definitions')
    op.drop_index(op.f('ix_feature_snapshots_session_id'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_table('experiments')
    op.drop_index('uq_exp_session', table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_session_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_experiment_id'), table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


# ---- pgvector (postgres only): native vector columns beside the JSON embeddings ----
def upgrade_pgvector() -> None:  # invoked by the 0002 migration on postgres
    pass
